export const NEXT_STEP_REQUEST_ACTION = 'NEXT_STEP_REQUEST';
export const PREVIOUS_STEP_REQUEST_ACTION = 'PREVIOUS_STEP_REQUEST';
export const RESET_WIZARD_REQUEST_ACTION = 'RESET_WIZARD_REQUEST';

export const UPDATE_VALUE_REQUEST_ACTION = 'UPDATE_VALUE_REQUEST';

export const SEARCH_PRODUCTS_REQUEST_ACTION = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS_ACTION = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE_ACTION = 'SEARCH_PRODUCTS_FAILURE';

export const UPDATE_DISPLAY_REQUEST_ACTION = 'UPDATE_DISPLAY_REQUEST';
export const UPDATE_DISPLAY_STEP3_REQUEST_ACTION = 'UPDATE_DISPLAY_STEP3_REQUEST';