export const INITIAL_VIEW_REQUEST_ACTION = 'INITIAL_VIEW_REQUEST';
export const INIT_WIZARD_REQUEST_ACTION = 'INIT_WIZARD_REQUEST';
export const NEXT_STEP_REQUEST_ACTION = 'NEXT_STEP_REQUEST';
export const PREVIOUS_STEP_REQUEST_ACTION = 'PREVIOUS_STEP_REQUEST';
export const RESET_WIZARD_REQUEST_ACTION = 'RESET_WIZARD_REQUEST';

export const STEP1_UPDATE_GENDER_ACTION = 'STEP1_UPDATE_GENDER_ACTION';
export const STEP1_UPDATE_AGE_ACTION = 'STEP1_UPDATE_AGE_ACTION';
export const STEP1_VALIDATION_ERRORS_ACTION = 'STEP1_VALIDATION_ERRORS_ACTION';
export const STEP1_CLEAR_VALIDATION_ERRORS_ACTION = 'STEP1_CLEAR_VALIDATION_ERRORS_ACTION';

export const STEP2_UPDATE_DISPLAY_ACTION = 'STEP2_UPDATE_DISPLAY_ACTION';

export const STEP3_UPDATE_DISPLAY_ACTION = 'STEP3_UPDATE_DISPLAY_ACTION';

export const STEP4_UPDATE_AMOUNT_ACTION = 'STEP4_UPDATE_AMOUNT_ACTION';

export const SEARCH_PRODUCTS_REQUEST_ACTION = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS_ACTION = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE_ACTION = 'SEARCH_PRODUCTS_FAILURE';
